[colors.primary]
background = "#111214"
foreground = "#d4d4d4"
dim_foreground = "#80868f"
bright_foreground = "#d4d4d4"

[colors.cursor]
text = "#111214"
cursor = "#C80050"

[colors.vi_mode_cursor]
text = "#111214"
cursor = "#C80050"

[colors.search.matches]
foreground = "#111214"
background = "#80868f"

[colors.search.focused_match]
foreground = "#111214"
background = "#C80050"

[colors.footer_bar]
foreground = "#111214"
background = "#181a1d"

[colors.hints.start]
foreground = "#111214"
background = "#C80050"

[colors.hints.end]
foreground = "#111214"
background = "#80868f"

[colors.selection]
text = "#111214"
background = "#2a2d33"

[colors.normal]
black = "#26292f"
red = "#780030"
green = "#C80050"
yellow = "#A00040"
blue = "#C80050"
magenta = "#A00040"
cyan = "#C80050"
white = "#d4d4d4"

[colors.bright]
black = "#26292f"
red = "#780030"
green = "#C80050"
yellow = "#A00040"
blue = "#C80050"
magenta = "#A00040"
cyan = "#C80050"
white = "#d4d4d4"

[[colors.indexed_colors]]
index = 16
color = "#A00040"

[[colors.indexed_colors]]
index = 17
color = "#780030"
