theme[main_bg]="#111214"

theme[main_fg]="#d4d4d4"

theme[title]="#d4d4d4"

theme[hi_fg]="#C80050"

theme[selected_bg]="#181a1d"

theme[selected_fg]="#C80050"

theme[inactive_fg]="#80868f"

theme[graph_text]="#d4d4d4"

theme[meter_bg]="#111214"

theme[proc_misc]="#d4d4d4"

theme[cpu_box]="#C80050"
theme[mem_box]="#C80050"
theme[net_box]="#A00040"
theme[proc_box]="#C80050"

theme[div_line]="#26292f"

theme[temp_start]="#C80050"
theme[temp_mid]="#A00040"
theme[temp_end]="#780030"

theme[cpu_start]="#C80050"
theme[cpu_mid]="#A00040"
theme[cpu_end]="#780030"

theme[free_start]="#C80050"
theme[free_mid]="#A00040"
theme[free_end]="#780030"

theme[cached_start]="#C80050"
theme[cached_mid]="#A00040"
theme[cached_end]="#780030"

theme[available_start]="#A00040"
theme[available_mid]="#780030"
theme[available_end]="#500020"

theme[used_start]="#C80050"
theme[used_mid]="#A00040"
theme[used_end]="#780030"

theme[download_start]="#C80050"
theme[download_mid]="#A00040"
theme[download_end]="#780030"

theme[upload_start]="#C80050"
theme[upload_mid]="#A00040"
theme[upload_end]="#780030"

theme[process_start]="#C80050"
theme[process_mid]="#A00040"
theme[process_end]="#780030"
