background = 111214
foreground = d4d4d4

# Cursor
cursor-color = C80050
cursor-text = 111214
cursor-style = block
cursor-style-blink = false

# Selection
selection-background = 1f2226
selection-foreground = d4d4d4

# Normal colors
palette = 0=#26292f
palette = 1=#ff0055
palette = 2=#00ff66
palette = 3=#00eeff
palette = 4=#A00040
palette = 5=#bd93f9
palette = 6=#00eeff
palette = 7=#e0e0e0

# Bright colors
palette = 8=#4d4d4d
palette = 9=#ff5588
palette = 10=#55ff99
palette = 11=#55ffff
palette = 12=#C80050
palette = 13=#e0b0ff
palette = 14=#55ffff
palette = 15=#ffffff

# Window
window-padding-x = 12
window-padding-y = 10
window-decoration = false

# Misc
mouse-hide-while-typing = true
copy-on-select = false
