$activeBorderColor = rgba(ff0055ee) rgba(C80050ee) 45deg
$inactiveBorderColor = rgba(26292fee)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}

decoration {
    rounding = 4
    rounding_power = 4.0
    dim_inactive = false

    blur {
        xray = true
        size = 10
        passes = 2
        noise = 0
        contrast = 1
        popups = true
        popups_ignorealpha = 0.6
        input_methods = true
        input_methods_ignorealpha = 0.8
    }
}
