# Colors
background            #111214
foreground            #d4d4d4
dim_opacity           0.6

# Cursor
cursor                #C80050
cursor_text_color     #111214
cursor_shape          block
cursor_blink_interval 0

# Selection
selection_background  #1f2226
selection_foreground  #d4d4d4

# URL underline
url_color             #C80050

# Normal colors
color0  #26292f
color1  #ff0055
color2  #00ff66
color3  #00eeff
color4  #A00040
color5  #bd93f9
color6  #00eeff
color7  #e0e0e0

# Bright colors
color8  #4d4d4d
color9  #ff5588
color10 #55ff99
color11 #55ffff
color12 #C80050
color13 #e0b0ff
color14 #55ffff
color15 #ffffff

# Window
window_padding_width   12 10
hide_window_decorations yes
background_opacity     1.0

# Tab bar
tab_bar_style                separator
tab_bar_background           #111214
tab_bar_margin_color         #111214
active_tab_background        #111214
active_tab_foreground        #d4d4d4
active_tab_font_style        bold
inactive_tab_background      #181a1d
inactive_tab_foreground      #80868f
inactive_tab_font_style      normal

# Misc
enable_audio_bell            no
mouse_hide_wait              3.0
copy_on_select               no
