return {
	{
		"Mofiqul/dracula.nvim",
		name = "dracula",
		priority = 1000,
		lazy = false,
		opts = {
			colors = {
				bg = "#111214",
				fg = "#d4d4d4",
				selection = "#181a1d",
				comment = "#80868f",
				red = "#780030",
				orange = "#A00040",
				yellow = "#A00040",
				green = "#C80050",
				purple = "#C80050",
				cyan = "#A00040",
				pink = "#780030",
				bright_red = "#780030",
				bright_green = "#C80050",
				bright_yellow = "#A00040",
				bright_blue = "#A00040",
				bright_magenta = "#780030",
				bright_cyan = "#A00040",
				bright_white = "#d4d4d4",
				menu = "#181a1d",
				visual = "#1f2226",
				gutter_fg = "#80868f",
				nontext = "#26292f",
				white = "#d4d4d4",
				black = "#111214",
			},
			transparent_bg = true,
			italic_comment = true,
			overrides = function(colors)
				return {
					AlphaHeader = { fg = colors.purple },
					AlphaButtons = { fg = colors.cyan },
					AlphaShortcut = { fg = colors.pink },
					AlphaFooter = { fg = colors.orange },
					DashboardHeader = { fg = colors.purple },
					DashboardCenter = { fg = colors.cyan },
					DashboardShortCut = { fg = colors.pink },
					DashboardFooter = { fg = colors.orange },
					LineNr = { fg = colors.comment },
					CursorLineNr = { fg = colors.purple },
					CursorLine = { bg = "#181a1d" },
					FloatBorder = { fg = "#26292f", bg = "#181a1d" },
					NormalFloat = { bg = "#181a1d" },
					Keyword = { fg = colors.purple },
					Function = { fg = colors.cyan },
					Type = { fg = colors.pink },
					["@function"] = { fg = colors.cyan },
					["@keyword"] = { fg = colors.purple },
					["@type"] = { fg = colors.pink },
					["@string"] = { fg = colors.orange },
					Directory = { fg = colors.purple },
					Search = { bg = "#1f2226", fg = colors.purple },
					IncSearch = { bg = colors.purple, fg = colors.black },
					Visual = { bg = "#1f2226" },
					LspReferenceText = { bg = "#1f2226" },
					LspReferenceRead = { bg = "#1f2226" },
					LspReferenceWrite = { bg = "#1f2226" },
					TelescopeSelectionCaret = { fg = colors.purple },
					TelescopeSelection = { fg = colors.purple, bg = "#181a1d" },
					TelescopePromptPrefix = { fg = colors.cyan },
					TelescopeBorder = { fg = "#26292f", bg = "#111214" },
					TelescopePromptNormal = { bg = "#181a1d" },
					TelescopePromptBorder = { fg = "#26292f", bg = "#181a1d" },
					NeoTreeDirectoryIcon = { fg = colors.cyan },
					NeoTreeDirectoryName = { fg = colors.purple },
					GitSignsAdd = { fg = colors.green },
					GitSignsChange = { fg = colors.cyan },
					GitSignsDelete = { fg = colors.red },
					IndentBlanklineChar = { fg = colors.nontext },
					IndentBlanklineContextChar = { fg = colors.comment },
					StatusLine = { bg = colors.black },
					TabLine = { bg = colors.black },
					TabLineSel = { fg = colors.purple, bg = "#181a1d" },
					NoiceCmdlineIcon = { fg = colors.cyan },
					NoiceCmdlinePopupBorder = { fg = "#26292f" },
					NoiceCmdlinePopup = { bg = "#181a1d" },
				}
			end,
		},
	},
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "dracula",
		},
	},
	{
		"nvim-lualine/lualine.nvim",
		opts = function(_, opts)
			local colors = {
				bg = "#111214",
				elevated = "#181a1d",
				fg = "#d4d4d4",
				ruby = "#C80050",
				ruby_dim = "#A00040",
				ruby_dark = "#780030",
				border = "#26292f",
				muted = "#80868f",
			}
			opts.options = opts.options or {}
			opts.options.theme = {
				normal = {
					a = { bg = colors.ruby, fg = colors.bg },
					b = { bg = colors.elevated, fg = colors.fg },
					c = { bg = colors.bg, fg = colors.fg },
				},
				insert = {
					a = { bg = colors.ruby_dim, fg = colors.bg },
					b = { bg = colors.elevated, fg = colors.fg },
					c = { bg = colors.bg, fg = colors.fg },
				},
				visual = {
					a = { bg = colors.ruby_dark, fg = colors.bg },
					b = { bg = colors.elevated, fg = colors.fg },
					c = { bg = colors.bg, fg = colors.fg },
				},
				replace = {
					a = { bg = colors.ruby_dark, fg = colors.bg },
					b = { bg = colors.elevated, fg = colors.fg },
					c = { bg = colors.bg, fg = colors.fg },
				},
				command = {
					a = { bg = colors.ruby_dim, fg = colors.bg },
					b = { bg = colors.elevated, fg = colors.fg },
					c = { bg = colors.bg, fg = colors.fg },
				},
				inactive = {
					a = { bg = colors.bg, fg = colors.muted },
					b = { bg = colors.bg, fg = colors.muted },
					c = { bg = colors.bg, fg = colors.muted },
				},
			}
		end,
	},
}
