return {
	{
		"Mofiqul/dracula.nvim",
		name = "dracula",
		priority = 1000,
		lazy = false,
		opts = {
			colors = {
				bg = "#111214",
				fg = "#d4d4d4",
				selection = "#181a1d",
				comment = "#80868f",
				red = "#780030",
				orange = "#A00040",
				yellow = "#A00040",
				green = "#C80050",
				purple = "#C80050",
				cyan = "#C80050",
				pink = "#C80050",
				bright_red = "#780030",
				bright_green = "#C80050",
				bright_yellow = "#A00040",
				bright_blue = "#C80050",
				bright_magenta = "#A00040",
				bright_cyan = "#C80050",
				bright_white = "#d4d4d4",
				menu = "#111214",
				visual = "#181a1d",
				gutter_fg = "#80868f",
				nontext = "#26292f",
				white = "#d4d4d4",
				black = "#111214",
			},
			transparent_bg = true,
			italic_comment = true,
			overrides = function(colors)
				return {
					AlphaHeader = { fg = colors.purple },
					AlphaButtons = { fg = colors.purple },
					AlphaShortcut = { fg = colors.purple },
					AlphaFooter = { fg = colors.purple },
					DashboardHeader = { fg = colors.purple },
					DashboardCenter = { fg = colors.purple },
					DashboardShortCut = { fg = colors.purple },
					DashboardFooter = { fg = colors.purple },
					LineNr = { fg = colors.comment },
					CursorLineNr = { fg = colors.purple, style = { "bold" } },
					Keyword = { fg = colors.purple },
					Function = { fg = colors.purple },
					Type = { fg = colors.purple },
					["@function"] = { fg = colors.purple },
					["@keyword"] = { fg = colors.purple },
					["@type"] = { fg = colors.purple },
					Directory = { fg = colors.purple },
					Search = { bg = colors.selection, fg = colors.purple },
					IncSearch = { bg = colors.purple, fg = colors.black },
					Visual = { bg = colors.selection, style = { "bold" } },
					LspReferenceText = { bg = colors.selection },
					LspReferenceRead = { bg = colors.selection },
					LspReferenceWrite = { bg = colors.selection },
					TelescopeSelectionCaret = { fg = colors.purple },
					TelescopeSelection = { fg = colors.purple, bg = colors.selection, style = { "bold" } },
					TelescopePromptPrefix = { fg = colors.purple },
					TelescopeBorder = { fg = colors.purple },
					NeoTreeDirectoryIcon = { fg = colors.purple },
					NeoTreeDirectoryName = { fg = colors.purple },
					GitSignsAdd = { fg = colors.green },
					GitSignsChange = { fg = colors.purple },
					GitSignsDelete = { fg = colors.red },
					IndentBlanklineChar = { fg = colors.nontext },
					IndentBlanklineContextChar = { fg = colors.purple },
					StatusLine = { bg = colors.black },
					TabLine = { bg = colors.black },
					TabLineSel = { fg = colors.purple, bg = colors.black, style = { "bold" } },
					NoiceCmdlineIcon = { fg = colors.purple },
					NoiceCmdlinePopupBorder = { fg = colors.purple },
				}
			end,
		},
	},
	{
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "dracula",
		},
	},
}
